# Generated by Django 3.1.4 on 2021-01-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20210103_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingre',
            field=models.TextField(),
        ),
    ]
