# Generated by Django 3.1.4 on 2021-01-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20210105_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingre',
            field=models.CharField(max_length=100),
        ),
    ]
